# Working with numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,3,6,8,9])
print(a)

[1 3 6 8 9]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(5,)


In [7]:
b=np.array([[2,5],[1,6],[1,7],[9,5]])
print(b)

[[2 5]
 [1 6]
 [1 7]
 [9 5]]


In [8]:
print(b.shape)

(4, 2)


In [9]:
b[1,1]

6

#### Create array of  zeroes , ones and custom

In [10]:
a=np.zeros((3,3))
print(a)
print(type(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [11]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


###### Create custom array

In [12]:
c=np.full((3,2),6)
print(c)

[[6 6]
 [6 6]
 [6 6]]


###### Identity matrix - Size square matrix

In [14]:
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###### Random matrix

In [15]:
randomMatrix=np.random.random((4,3))
print(randomMatrix)

[[0.38534858 0.60874524 0.18056595]
 [0.06877224 0.77049208 0.25562146]
 [0.59745124 0.33380374 0.89922848]
 [0.78200326 0.85957619 0.98654601]]


Print verticle colunmn

In [16]:
print(d[:,1])

[0. 1. 0. 0.]


In [18]:
print(randomMatrix[:,2])    

[0.18056595 0.25562146 0.89922848 0.98654601]


In [20]:
print(randomMatrix[1])

[0.06877224 0.77049208 0.25562146]


Print some part of row

In [21]:
print(randomMatrix[2,1:3])

[0.33380374 0.89922848]


Print a part of column

In [22]:
print(randomMatrix[1:4,2])

[0.25562146 0.89922848 0.98654601]


###### Set any value to row or column

In [24]:
a=np.zeros((3,3))
print(a)
a[:,1]=4
a[2,:]=7
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 4. 0.]
 [0. 4. 0.]
 [7. 7. 7.]]


In [26]:
print(a.dtype)

float64


In [27]:
b=np.zeros((2,2),dtype=np.int64)
print(b)
print(b.dtype)

[[0 0]
 [0 0]]
int64


###### Mathematical operator

In [3]:
x=np.array([[2,3],[5,6]])
y=np.array([[8,3],[8,6]])
print(x+y)

[[10  6]
 [13 12]]


In [5]:
print(np.add(x,y))

[[10  6]
 [13 12]]


In [8]:
print(np.subtract(x,y))
print(x-y)

[[-6  0]
 [-3  0]]
[[-6  0]
 [-3  0]]


In [11]:
print(x*y)
print(np.multiply(x,y))

[[16  9]
 [40 36]]
[[16  9]
 [40 36]]


In [12]:
print(x/y)
print(np.divide(x,y))

[[0.25  1.   ]
 [0.625 1.   ]]
[[0.25  1.   ]
 [0.625 1.   ]]


###### Matrix multiplication / Dot product

In [13]:
print(x.dot(y))
print(np.dot(x,y))

[[40 24]
 [88 51]]
[[40 24]
 [88 51]]


###### Multiplication of vectors

In [14]:
x=np.array([2,7,4,2])
y=np.array([3,6,2,4])
print(x.dot(y))

64


In [16]:
print(sum(x))

15


In [19]:
x=np.array([[2,3],[7,2]])

In [20]:
print(np.sum(x))

14


axis=1 is along row 
axis=0 is along column

In [21]:
print(np.sum(x,axis=0))

[9 5]


In [22]:
print(np.sum(x,axis=1))

[5 9]


In [24]:
print(x)
print(y)

[[2 3]
 [7 2]]
[3 6 2 4]


In [26]:
x=([3,8,3,1])

In [27]:
print(np.stack((x,y),axis=0))

[[3 8 3 1]
 [3 6 2 4]]


In [28]:
print(np.stack((x,y),axis=1))

[[3 3]
 [8 6]
 [3 2]
 [1 4]]


###### Reshape the numpy array

In [29]:
 a=np.stack((x,y),axis=0)

In [31]:
print(a)

[[3 8 3 1]
 [3 6 2 4]]


In [39]:
a=a.reshape((8,1))
print(a)

[[3]
 [8]
 [3]
 [1]
 [3]
 [6]
 [2]
 [4]]


In [40]:
a=a.reshape((4,2))
print(a)

[[3 8]
 [3 1]
 [3 6]
 [2 4]]


In [41]:
a=a.reshape((8,))
print(a)

[3 8 3 1 3 6 2 4]


In [42]:
a=a.reshape((4,-1)) #if don't want to figure out the row/column no. provide other along with -1
print(a)

[[3 8]
 [3 1]
 [3 6]
 [2 4]]


In [44]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


### Random numpy module

- rand : random values given in a given shape
- randn : return a sample/samples from "standard normal" distribution
- randint : return random integers from lower(inclusive) to higher (exclusive)
- random : return random floats in half-interval [0.0,1.0)
- choice : generates random sample from given 1D array
- shuffle : shuffles the content of sequence

In [45]:
np.random.shuffle(a)
print(a)

[ 8  5 12 11 14  9  7 10  6 13]


In [46]:
a=np.random.rand(2,3)
print(a)

[[0.17101794 0.23454864 0.44145405]
 [0.23829762 0.01403905 0.62530333]]


In [48]:
a=np.random.randn(2,3)
print(a)

[[ 1.20592399  0.8659571   1.20610759]
 [-0.68725379 -0.20191226 -0.95459361]]


In [50]:
a=np.random.randint(2,10,5)   #randint(lower,higher,no_of_elements)
print(a) 

[6 7 3 4 6]


In [55]:
a=np.random.choice([3,8,2,7,9,5])
print(a)

2


In [70]:
a=np.random.random(5)
print(a)

[0.22957721 0.53441391 0.91396202 0.45720481 0.43069857]


if want to generate same random no. each time then use np.random.seed(1)

In [71]:
np.random.seed(1)

In [72]:
np.random.shuffle(a)
print(a)

[0.91396202 0.53441391 0.43069857 0.22957721 0.45720481]


In [73]:
np.random.shuffle(a)
print(a)

[0.91396202 0.43069857 0.45720481 0.22957721 0.53441391]


###### Statistic and More Numpy functions

In [74]:
a=np.array([[2,4,6,1],[7,8,4,1]])

In [75]:
print(np.min(a))

1


In [76]:
print(np.min(a,axis=0))

[2 4 4 1]


In [77]:
print(np.min(a,axis=1))

[1 1]


In [78]:
print(np.max(a,axis=0))

[7 8 6 1]


In [79]:
print(np.mean(a))

4.125


In [80]:
print(np.mean(a,axis=0))

[4.5 6.  5.  1. ]


In [81]:
print(np.mean(a,axis=1))

[3.25 5.  ]


In [82]:
print(np.median(a))

4.0


###### Average has Weight

In [96]:
c=np.arange(5)+1
print(c)
w=np.array([1,5,3,2,4])
print(np.mean(c))
print(np.average(c,weights=w))    #(1*1+2*5+3*3+2*4+4*5)/15=(2+10+9+8+20)/15=49/15

[1 2 3 4 5]
3.0
3.2


If weight is 1 then mean=average

In [97]:
w=np.array([1,1,1,1,1])
print(np.mean(c))
print(np.average(c,weights=w))

3.0
3.0


###### Standard deviation and variance

- S.D=√(1/n)Σ(Xi - mean)²
- variance=(S.D)²

In [100]:
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.4142135623730951


In [101]:
# Inbuilt func
print(np.std(c))

1.4142135623730951


In [102]:
print(myStd**2)
print(np.var(c))

2.0000000000000004
2.0
